---
title: Lara J. Martin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: laramar@seas.upenn.edu
description: Homepage to Dr. Lara J. Martin.
baseurl: ''
url: https://laramartin.net
twitter_username: LangTechLara
github_username: lara-martin
theme: minima
plugins:
- jekyll-feed
- jekyll-scholar
markdown: kramdown
highlighter: rouge
